import { Inter } from "next/font/google";
import "./globals.css";
import { Header, TopLoader } from "@/components";
import ReduxProvider from "./ReduxProvider";
import MobileNavigation from "@/components/header/MobileNavigation";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import WalletProvider from "./WalletProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AuthProvider from "./AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProvider>
          <ReduxProvider>
            <AuthProvider>
              <Header />
              <TopLoader />
              <Toaster />
              <div className="block xl:hidden">
                <MobileNavigation />
              </div>
              <div className="container-fluid mx-auto">{children}</div>
            </AuthProvider>
          </ReduxProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
